name: saas_framework_flutter
repository: https://github.com/longvhv/saas-framework-flutter

packages:
  - packages/**
  - apps/**

command:
  bootstrap:
    # Run pub get in parallel for all packages
    runPubGetInParallel: true
    # Automatically link local packages
    usePubspecOverrides: true

scripts:
  # Bootstrap all packages
  bootstrap:
    run: melos bootstrap
    description: Install dependencies for all packages

  # Analyze all packages
  analyze:
    run: melos exec -- flutter analyze
    description: Run flutter analyze for all packages
    packageFilters:
      dirExists: lib

  # Format all Dart files
  format:
    run: melos exec -- dart format .
    description: Format all Dart files
    packageFilters:
      dirExists: lib

  # Run tests for all packages
  test:
    run: melos exec -- flutter test
    description: Run tests for all packages
    packageFilters:
      dirExists: test

  # Clean all packages
  clean:
    run: melos exec -- flutter clean
    description: Clean all packages
    packageFilters:
      flutter: true

  # Build all apps
  build:
    run: melos exec -- flutter build apk
    description: Build all apps
    packageFilters:
      scope: "app*"

  # Get dependencies
  get:
    run: melos exec -- flutter pub get
    description: Run pub get for all packages
    packageFilters:
      flutter: true

  # Upgrade dependencies
  upgrade:
    run: melos exec -- flutter pub upgrade
    description: Upgrade dependencies for all packages
    packageFilters:
      flutter: true

  # Generate code (json_serializable, etc.)
  generate:
    run: melos exec -- flutter pub run build_runner build --delete-conflicting-outputs
    description: Run code generation
    packageFilters:
      dependsOn: "build_runner"

  # Dry run publish
  publish:dry-run:
    run: melos publish --dry-run
    description: Dry run package publishing

  # Check for outdated dependencies
  outdated:
    run: melos exec -- flutter pub outdated
    description: Check for outdated dependencies
